<?xml version="1.0" encoding="Windows-1252"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="7.10"
	Name="{$projName}"
	ProjectGUID="{ldelim}1E68C046-26D7-4AD9-BEF2-590C6B99B40A{rdelim}"
	RootNamespace="{$projName}"
	SccProjectName=""
	SccLocalPath="">
	<Platforms>
		<Platform
			Name="Win32"/>
	</Platforms>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="../../Link/$(ConfigurationName).$(PlatformName)"
			IntermediateDirectory="$(OutDir)/$(ProjectName)"
			ConfigurationType="1"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE">
			<Tool
				Name="VCCLCompilerTool"
				Optimization="0"
				AdditionalIncludeDirectories="../../Lib/xiph/include;/lib/SDL/include;../../Lib/directx8;../../Lib/zlib;../../Lib/lungif;../../Lib/lpng;../../Lib/ljpeg;../../Lib/openal/win32;../../Source"
				PreprocessorDefinitions="{$projDefines}TORQUE_DEBUG;UNICODE;TORQUE_DEBUG_GUARD;_CRT_SECURE_NO_DEPRECATE"
				BasicRuntimeChecks="3"
				RuntimeLibrary="0"
				RuntimeTypeInfo="TRUE"
				UsePrecompiledHeader="0"
				AssemblerListingLocation="$(OutDir)"
				ProgramDataBaseFileName="$(OutDir)/$(ProjectName).pdb"
				BrowseInformation="1"
				SuppressStartupBanner="TRUE"
				DebugInformationFormat="4"
				CompileAs="2"/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCLinkerTool"
				AdditionalDependencies="COMCTL32.LIB COMDLG32.LIB USER32.LIB ADVAPI32.LIB GDI32.LIB WINMM.LIB WSOCK32.LIB vfw32.lib ogg_static.lib theora_static.lib vorbis_static.lib Imm32.lib unicows.lib shell32.lib shlwapi.lib ole32.lib"
				OutputFile="../../../tgb/{$additionalExePath}{$projName}_DEBUG.exe"
				LinkIncremental="2"
				SuppressStartupBanner="TRUE"
				AdditionalLibraryDirectories="../../Lib/xiph/win32;../../Lib/SDL/win32;../../Lib/unicode;../../lib/directx8"
				IgnoreDefaultLibraryNames="LIBC,LIBCD"
				GenerateDebugInformation="TRUE"
				ProgramDatabaseFile="$(OutDir)/{$projName}.pdb"
				SubSystem="2"
				TargetMachine="1"/>
			<Tool
				Name="VCMIDLTool"
				TypeLibraryName="$(OutDir)/{$projName} SDK.tlb"
				HeaderFileName=""/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				PreprocessorDefinitions="_DEBUG"
				Culture="1033"/>
			<Tool
				Name="VCWebServiceProxyGeneratorTool"/>
			<Tool
				Name="VCXMLDataGeneratorTool"/>
			<Tool
				Name="VCWebDeploymentTool"/>
			<Tool
				Name="VCManagedWrapperGeneratorTool"/>
			<Tool
				Name="VCAuxiliaryManagedWrapperGeneratorTool"/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="../../Link/$(ConfigurationName).$(PlatformName)"
			IntermediateDirectory="$(OutDir)/$(ProjectName)"
			ConfigurationType="1"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			WholeProgramOptimization="FALSE">
			<Tool
				Name="VCCLCompilerTool"
				Optimization="1"
				InlineFunctionExpansion="1"
				AdditionalIncludeDirectories="../../Lib/xiph/include;/lib/SDL/include;../../Lib/directx8;../../Lib/zlib;../../Lib/lungif;../../Lib/lpng;../../Lib/ljpeg;../../Lib/openal/win32;../../Source"
				PreprocessorDefinitions="{$projDefines}UNICODE;_CRT_SECURE_NO_DEPRECATE"
				StringPooling="TRUE"
				RuntimeLibrary="0"
				EnableFunctionLevelLinking="TRUE"
				RuntimeTypeInfo="TRUE"
				UsePrecompiledHeader="0"
				AssemblerListingLocation="$(OutDir)"
				ProgramDataBaseFileName="$(OutDir)/{$projName}.pdb"
				BrowseInformation="1"
				WarningLevel="1"
				SuppressStartupBanner="TRUE"
				DebugInformationFormat="3"
				CompileAs="2"/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCLinkerTool"
				AdditionalDependencies="COMCTL32.LIB COMDLG32.LIB USER32.LIB ADVAPI32.LIB GDI32.LIB WINMM.LIB WSOCK32.LIB vfw32.lib ogg_static.lib theora_static.lib vorbis_static.lib Imm32.lib unicows.lib shell32.lib shlwapi.lib ole32.lib"
				OutputFile="../../../tgb/{$additionalExePath}{$projName}.exe"
				LinkIncremental="1"
				SuppressStartupBanner="TRUE"
				AdditionalLibraryDirectories="../../Lib/xiph/win32;../../Lib/SDL/win32;../../Lib/unicode;../../lib/directx8"
				IgnoreDefaultLibraryNames="LIBC"
				GenerateDebugInformation="TRUE"
				ProgramDatabaseFile="$(OutDir)/{$projName}.pdb"
				SubSystem="2"
				TargetMachine="1"/>
			<Tool
				Name="VCMIDLTool"
				TypeLibraryName="$(OutDir)/{$projName} SDK.tlb"
				HeaderFileName=""/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				PreprocessorDefinitions="NDEBUG"
				Culture="1033"/>
			<Tool
				Name="VCWebServiceProxyGeneratorTool"/>
			<Tool
				Name="VCXMLDataGeneratorTool"/>
			<Tool
				Name="VCWebDeploymentTool"/>
			<Tool
				Name="VCManagedWrapperGeneratorTool"/>
			<Tool
				Name="VCAuxiliaryManagedWrapperGeneratorTool"/>
		</Configuration>
	</Configurations>
	<References>
	</References>
	<Files>
		<Filter
			Name="Source Files"
			Filter="cpp;c;cxx;rc;def;r;odl;idl;hpj;bat;cc">
			<File
				RelativePath="T2D SDK.rc">
			</File>
			<File
				RelativePath=".\vc7fix.cpp">
			</File>
{assign var="dirWalk" value=$fileArray}
{include file="vc2k3_fileRecurse.tpl" dirWalk=$dirWalk depth=2 dirPath=$projOutput.baseDir}
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
